### ISSUE TITLE
[Suggestion] use API instead of selenium

### ISSUE THREAD

**Issue by RealPacket** [jvherck/roastedbyai#1]
Under the hood, when you decide to send a message, a POST request is sent to `https://roastedby.ai/api/generate`, with JSON data for the body.

Here's an example:
```json
{
  "userMessage": {
    "role": "user",
    "content": "Ok"
  },
  "history": [
    {
      "role": "assistant",
      "content": "Hello there. I'm here to roast you."
    }
  ],
  "style": "default"
}
```
NOTE: if you change the first assistant message's content, it will behave differently (so it's like a system prompt)
The response JSON only has one field, the `content` string.

Here's an example (it's the response returned when you submit the JSON data I provided for a request body example):
```json
{
  "content": "Alright, let's do this. I hope you're ready because I'm about to roast you so hard, you'll be begging for aloe vera. Let's go!"
}
```

But, right now, this doesn't add up the different messages, so how would we?
First, we store the history of the conversation, every time we send a new message,
we add a new item to the array of messages (they have the `role`, and the `content`), and when the "assistant".
Second, whenever we want to send a new message, store the assistant (more like roastsistant)'s response (set `role` to assistant, and `content` to the content field provided in the response JSON).

Also, you might have noticed the `style` property, that correlates to the `style` dropdown. Here's all the possible entries it could be:
`default` -- default style
`crypto_bro` -- Crypto Douche
`new_york` -- New york
`south_london`  -- South London
`surfer_dude` -- Surfer Dude
`valley_girl` -- Valley Girl
`adult` -- ADULT (18+)

You can dump them by looping through every `option` in the style dropdown and adding their `value` to the dump list.

![every option having a value that can be used in the "style" string in the JSON body](https://github.com/jvherck/roastedbyai/assets/107498533/037c2c9a-90dc-481d-89b5-daac3e1a40b8)

Using the API instead of selenium will improve performance, as you only will need to send a request to an API instead of starting a new browser instance, selenium patching the browser, ten more years later (yes, I am using a hyperbole, it won't take 10 years), wait for other external resources that the website needs, etc.

**Comment by jvherck** [comment]
Thank you for this very clear and detailed feedback. I've looked for a long time if the website had any api and never found any so I figured I'd just use Selenium for it, which does make it slower and not as easy to use. 

As soon as I have time I will rewrite the package and use the api instead. Thank you for letting me know about the api!

**Comment by RealPacket** [comment]
I found it using dev tools (you do need to resize it if it's on the bottom, as some UI elements might overlap with the message box, *for some reason*).

**Comment by jvherck** [comment]
The new update is out and way faster. Thanks again for your help! 
If you can encounter any errors or bugs, please do open a new issue with your feedback.
