### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by jvherck** [jvherck/roastedbyai#2]
The `terminal_commands.txt` file is not in `.gitignore`. Is it also really necessary to include the build folder?

**Comment by RealPacket** [comment]
Version control is for source, not binaries, so probably.

**Comment by naghim** [comment]
Hi, Adding my two cents here. The `build`, `dist`, and `roastedbyai.egg-info` folders should also be added to the `.gitignore` file. The `terminal_commands.txt` file can remain, though it might be better to change its extension to `.sh` to match its content. 😄
